### ISSUE TITLE
Polling frequency

### ISSUE THREAD

**Issue by rfontijn** [myTselection/youfone_be#17]
After using this component for two weeks now, I have the idea that youfone blocked my IP since I have troubles with connecting to my.youfone.nl

I can imagine that they could do this if I do too much requests to their api.
What is the default frequency currently? And how can I adjust this?

**Comment by myTselection** [comment]
current frequency is 15minutes. So far this is only hard coded and not configurable

**Comment by myTselection** [comment]
Probably linked to issues #18, different users seems to have issues to login for NL accounts. Could you please try again with release 4.1.1 and report if it works now?
thanks!
