### ISSUE TITLE
Integration not working - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by prolife86** [myTselection/youfone_be#20]
It might be just me, if so, please let me know.

I was using this integration (NL part of YouFone) for a few months now
HA is running in a docker on Unraid with HACS installed.
It was working well until the update for HA: Core 2023.11.3 / Frontend 20231030.2.

Removing and readding does not resolve it.
I get the following error message:

> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:359
> Integration: Sensor (documentation, issues)
> First occurred: 13:29:35 (2 occurrences)
> Last logged: 13:29:36
> 
> Error while setting up youfone_be platform for sensor
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
>     yield
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 212, in connect_tcp
>     sock = socket.create_connection(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
>     yield
>   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
>     response = connection.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
>     stream = self._connect(request)
>              ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
>     stream = self._network_backend.connect_tcp(**kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 211, in connect_tcp
>     with map_exceptions(exc_map):
>   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ConnectError: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/youfone_be/sensor.py", line 93, in async_setup_entry
>     await dry_setup(hass, config, async_add_devices)
>   File "/config/custom_components/youfone_be/sensor.py", line 57, in dry_setup
>     await componentData._forced_update()
>   File "/config/custom_components/youfone_be/sensor.py", line 127, in _forced_update
>     self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/youfone_be/sensor.py", line 127, in <lambda>
>     self._user_details = await self._hass.async_add_executor_job(lambda: self._session.login(self._username, self._password))
>                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/youfone_be/utils.py", line 124, in login
>     response = self.s.get(f"https://my.youfone.{self._country}/login",headers=header,timeout=30)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1041, in get
>     return self.request(
>            ^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
>     response = self._send_handling_auth(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
>     response = self._send_handling_redirects(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
>     response = self._send_single_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
>     response = transport.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
>     with map_httpcore_exceptions():
>   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError: [Errno 111] Connection refused

**Comment by deeg61** [comment]
Same problem here (connection refused)

**Comment by myTselection** [comment]
ok, thanks for the feedback. I didn't have time yet to check in detail. As far as I can see now, it still seems to work as expected for Belgium. But I've seen in the past the rollout of changes to Youfone.nl are pushed to Belgium with some months in between, so we may probably expect the same issues soon for Belgium accounts. 
I'll try to check in more detail in the coming days.

**Comment by prolife86** [comment]
I do not know how, but it started working again.
Can it have been a disruption on Youfone's side?

**Comment by bezigebever** [comment]
I'm using it for Belgian subscription ans since today same issue...

**Comment by prolife86** [comment]
Right, it stopped working here as well again :(

https://pastebin.com/yrYuKkdD

**Comment by myTselection** [comment]
Hi, could you please test R4.4.0. I've added some sleep random number of seconds, trying to avoid IP blacklisting

**Comment by prolife86** [comment]
> Hi, could you please test R4.4.0. I've added some sleep random number of seconds, trying to avoid IP blacklisting

Installed, for now it still says httpx.ConnectError: [Errno 111] Connection refused
As I probably still am blacklisted.

https://pastebin.com/nMgMhnUn

**Comment by deeg61** [comment]
After install R.4.4.0 it worked yesterday perfect. But this morning it stopped working unfortunately :-(

**Comment by prolife86** [comment]
Issue is still present on 06Feb2024:
https://pastebin.com/dDYQaX1N

**Comment by deeg61** [comment]
After this morning updating to HA core 2024.2.0b9 the integration diden't work anymore

**Comment by myTselection** [comment]
I just upgraded to 2024.2.0 and still working fine for me.

are you using a BE or NL account?

**Comment by deeg61** [comment]
I'm using the nl version

**Comment by prolife86** [comment]
> I'm using the nl version

I was using NL, but as it was no working for some time now I removed the integration three days ago.
I do want to thank the @myTselection for all efforts.

**Comment by deeg61** [comment]
I don't want to remove it, because I like it to much :-) Hope that @myTselection will find an solution like he always does....

**Comment by Pammetje** [comment]
It is because my.youfone.nl gets blocked (some sort of DDOS protection) The integration needs te be changed that it queries my.youfone.nl only one or a few times per day.

**Comment by myTselection** [comment]
The update frequency is currently set to a random interval between 130 and 140min. This seems to work fine for youfone.be but still seems to get blocked from youfone.nl.
I'll check if I can make the update frequency interval configurable.

**Comment by Pammetje** [comment]
That would be great, thank you for your work

**Comment by deeg61** [comment]
Yes that would be great, thank you for the effort you put in this project

**Comment by myTselection** [comment]
R4.5.0 released.
I created a custom throttler that allows a non-hardcoded data refresh interval via configuration. Default interval is still 120min, but it can be changed during setup or using the 'configure' button. Please try with this and let me know which configuration would work for nl so I can add this info in the readme.

**Comment by deeg61** [comment]
unfortunately I still don't have any entities. I've already did 2 times an unstall and re-install but no luck. 
![youfone](https://github.com/myTselection/youfone_be/assets/86757357/e8a31bc1-665d-4e2a-825a-cbab287e9dc1)

**Comment by Pammetje** [comment]
Thank you very much, I will test it as soon as I am unblocked

**Comment by Pammetje** [comment]
The youfone NL API service changed, this integration is not working at the moment when using my.youfone.nl

**Comment by deeg61** [comment]
Thanks for the info Pammetje, then I don't have to try any longer to get it alive.

**Comment by myTselection** [comment]
Without l account I'm notable to analyse their API changes...

**Comment by deeg61** [comment]
I’m afraid youfone.be will soon follow the new policy of youfone.nl So i’t just a matter of time and you will be able to analyse the changes. We have to be patient...

**Comment by timdows** [comment]
> Without l account I'm notable to analyse their API changes...

I have an account, I can send you debug pages, html entries / api end-points if needed
The integration is not working due to changes in endpoint routing

Details:
Login post at:
https://my.youfone.nl/api/prov/authentication/login

Demo login (gives 401)
```
{"email":"test@test.com","password":"test"}
```

If succesfull logon, the data/call usage can be fetched from
```
curl 'https://my.youfone.nl/api/prov/Card/GetSimOnly' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,nl;q=0.7' \
  -H 'content-type: application/json' \
  -H 'cookie: lots-of-cookies' \
  -H 'dnt: 1' \
  -H 'origin: https://my.youfone.nl' \
  -H 'priority: u=1, i' \
  -H 'referer: https://my.youfone.nl/' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'securitykey: some-key-here' \
  -H 'user-agent: browser-agent' \
  --data-raw '{"customerId":12345-test,"msisdn":316-dutch-phonenr,"roleId":xyz}'
```

The issue is getting the security-key, I didn't see where this is send to my browser initially
