### ISSUE TITLE
New name Youfone -> Yoin

### ISSUE THREAD

**Issue by iwanvandaele** [myTselection/youfone_be#22]
The integration is not working anymore, is it because the new name launch? Are all the paths changed to https://my.yoin.be/login instead of https://my.youfone.be/login?

error code: 
ssert response.status_code == 200

**Comment by myTselection** [comment]
fixed in R5.0.0

**Comment by bezigebever** [comment]
@myTselection many thanks !

**Comment by iwanvandaele** [comment]
Great thx!!
