### ISSUE TITLE
Phone number has to be msisdn number

### ISSUE THREAD

**Issue by geertmeersman** [myTselection/youfone_be#3]
In the attributes, the phone number is taken from the account information, but it is not the phone number which is linked to the SIM.
Would be nice to see the msisdn available in the attributes, as this is the number we need.

**Comment by myTselection** [comment]
Thanks for the feedback Geert! It has been updated since release 1.1.2.

**Comment by geertmeersman** [comment]
Tested it and it is perfect for the call/sms sensor. You need also to change it for the internet sensor (line 263)

Thanks for changing it this swift 👍

**Comment by myTselection** [comment]
Thx, did it too quick ;)
