### ISSUE TITLE
Percentage, need to calculate?

### ISSUE THREAD

**Issue by geertmeersman** [myTselection/youfone_be#4]
Something I noticed... But it's for sure not linked to the way you implemented it, but we can share some thoughts on it...
For the Internet, the percentage calculation at Youfone side seems wrong. They indicate 5%, but I currently only used 54Mb of the 12288Mb. Are you sure the percentage value is refering to the used amount? But perhaps it's a calculation error at Youfone's side :-)
![image](https://user-images.githubusercontent.com/1844091/216784702-63d5ff3c-bcb1-47cb-9f72-56d77b921ca1.png)

**Comment by myTselection** [comment]
I noticed the same recently. It seems mainly an issue at start of a new period I believe. 
But I checked and this is the data shared by Youfone. 
Youfone is using this to show the progress bar/slider on their site.
I might add my own percentage calculation. Will check on it, but currently mainly busy with dev on my other intergration (bibliotheek.be ;))

**Comment by geertmeersman** [comment]
No worries and no rush. Perhaps I'll modify it and send you the code .

And bibliotheek I saw indeed in your projects this week and also added it,
will come in handy since my wife just got some books that she forgot about
😂

Op za 4 feb. 2023 20:41 schreef myT ***@***.***>:

**Comment by geertmeersman** [comment]
Correction done and tested for both ComponentInternetSensor and ComponentMobileSensor

```
        self._used_percentage = round(int(self._includedvolume_usage)/int(self._total_volume.split(" ")[0]),2)
```

So feel free to add it whenever you have time :-)

![image](https://user-images.githubusercontent.com/1844091/216927240-6b526a64-deca-4a94-8040-2405f20f5e84.png)

**Comment by myTselection** [comment]
added a multiply with 100 since it's already expected to be a percentage. Fixed since R1.2.1. Thanks for your support again Geert!
